[auth.external.google]
enabled = true
client_id = "559446038598-be5aebe197mmu3bhlhfmvkjukrecr72h.apps.googleusercontent.com"
secret = "env(SUPABASE_AUTH_EXTERNAL_GOOGLE_CLIENT_SECRET)"
skip_nonce_check = false